### ISSUE TITLE
`medium` parameter in the `gapfill` function

### ISSUE THREAD

**Issue by hariszaf** [MGXlab/DNNGIOR#2]
@danielriosgarza  
It seems there is a description for the `medium` parameter however there's no such parameter among the definition's argumetns.
Contrary, there's a `result_selection` argument that does not have a description.
Is the `medium` argument still necessary ? 	https://github.com/MGXlab/DNNGIOR/blob/c8ba450e6b390e3f02a63935f6fdafbf943a8d99/scripts/gapfill_function.py#L354

**Comment by danielriosgarza** [comment]
Solved. 

We should replace the gapfill_function.py scripts for the "Gapfill" class (https://github.com/MGXlab/DNNGIOR/blob/main/scripts/gapfill_class.py)

with this class we gapfill the model with the following simple steps:

```
#with a defined medium
draftModelPath = os.path.join(Path(os.getcwd()).parents[0], 'files', 'models', 'bh_ungapfilled_model.sbml')
trainedNNPath = os.path.join(Path(os.getcwd()).parents[0], 'files', 'NN', 'NN_MS.h5')
gf = Gapfill(draftModelPath, trainedNNPath, medium = def_med, objectiveName = 'bio1')
model_defMedium = gf.gapfilledModel.copy()

#with a complete medium
draftModelPath = os.path.join(Path(os.getcwd()).parents[0], 'files', 'models', 'bh_ungapfilled_model.sbml')
trainedNNPath = os.path.join(Path(os.getcwd()).parents[0], 'files', 'NN', 'NN_MS.h5')
gf = Gapfill(draftModelPath, trainedNNPath, medium = None, objectiveName = 'bio1')
model_completeMedium = gf.gapfilledModel.copy()


```

@Biomerene : the class above (as its previous functions) is hard coded for the modelSEED database. How did you gapfill with the carveme models?

**Comment by Biomerene** [comment]
I created a different hardcoded version for the BiGG database, I was working on creating a combined version (originally I wanted it to detect it automatically but it is probably easier to just take modeltype as an input).  I have not shared that code yet as I was still working on it. I can see if I can adapt the gap-fill class so it can do both.

**Comment by danielriosgarza** [comment]
awesome!
