### ISSUE TITLE
version conflict between reactions used and weights file

### ISSUE THREAD

**Issue by hariszaf** [MGXlab/DNNGIOR#3]
Hi @Biomerene, 
it is my belief that there is a conflict between your [`NN_MS.h5`](https://github.com/MGXlab/DNNGIOR/blob/main/files/NN/NN_MS.h5) and the [`rxn_ids_ModelSEED.npy`](https://github.com/MGXlab/DNNGIOR/blob/main/files/NN/rxn_ids_ModelSEED.npy) files.

The first has now 2,457 reactions while the latter 2,452. I guess you just need to update the `rxn_ids_ModelSEED.npy`? 

Just for your information, under the [`NN`](https://github.com/danielriosgarza/FastNNGapfiller/tree/main/files/NN) of the previous repo, there's no conflict and both files have 2,452 reactions

**Comment by Biomerene** [comment]
Ah yes, thanks for pointing it out I forgot to update the 'rxn_ids_ModelSEED.npy' file when I updated the neural network. In principle the ids are now saved with the network in the .h5 file so the 'rxn_ids_ModelSEED.npy' file might no longer be necessary, but I will have a look

**Comment by hariszaf** [comment]
Ah, ok great! 

I just noticed that a similar conflict happens for the [`NN_CM.h5`](https://github.com/MGXlab/DNNGIOR/blob/main/files/NN/NN_CM.h5) where's a slight difference in the number of reactions at [`rxn_ids_BiGG.npy`](https://github.com/MGXlab/DNNGIOR/blob/main/files/NN/rxn_ids_BiGG.npy). 

Thanks a lot!

**Comment by Biomerene** [comment]
I updated the files, it turned out that the network was slightly wrong (making predictions for some reactions I removed in an earlier version). It should not be synced up. I also renamed NN_CM as I think it should probably be BiGG rather than CarveMe because you would use the same for all models using BiGG ids.

**Comment by hariszaf** [comment]
Ok great! I ll use those files and I hope I ll open a PR reg #1 by the end of the week I hope. 
I consider this issue as done! :tada:
