### ISSUE TITLE
`result_selection` argument

### ISSUE THREAD

**Issue by hariszaf** [MGXlab/DNNGIOR#6]
@danielriosgarza @Biomerene 
do you think we should add `result_selection` as an argument on the `Gapfill` class?

https://github.com/MGXlab/DNNGIOR/blob/605c9b6a18a17a8942f38ec405ca5d7bd2ef34ec/scripts/gapfill_class.py#L19

**Comment by danielriosgarza** [comment]
No, not in my opinion. I think we should work towards removing this from
the code and always return the minimum set

**Comment by hariszaf** [comment]
Ok, cool! Thanks.
